---
- hosts: debian
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install common packages
      apt:
        name:
          - sysstat
          - netstat
          - vim
        state: latest